# Generated by Django 6.0.2 on 2026-03-31 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_instapost_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='image',
            field=models.FileField(upload_to='InstaPost/'),
        ),
        migrations.AlterField(
            model_name='instapost',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='tagged_post', to='myapp.instauser'),
        ),
        migrations.AlterField(
            model_name='instapost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instauser'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='myapp.instauser')),
                ('following_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_person', to='myapp.instauser')),
            ],
        ),
    ]
