# Generated by Django 6.0.2 on 2026-04-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
