# Generated by Django 6.0.2 on 2026-04-05 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_notifications_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='post_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.instapost'),
        ),
    ]
