# Generated by Django 6.0.2 on 2026-04-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notifications_post_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Unlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='myapp.instapost')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='myapp.instauser')),
            ],
        ),
    ]
