# Generated by Django 6.0.2 on 2026-04-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_like_unlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like_unlike',
            unique_together={('user_fk', 'post_fk')},
        ),
        migrations.CreateModel(
            name='InstaReels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='InstaReels/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instauser')),
            ],
        ),
    ]
