# Generated by Django 6.0.2 on 2026-04-14 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_like_unlike_unique_together_instareels'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='InstaStory/')),
                ('video', models.FileField(blank=True, null=True, upload_to='InstaStory/')),
                ('music', models.FileField(blank=True, null=True, upload_to='InstaStory/music/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('audience', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instauser')),
            ],
        ),
    ]
