# Generated by Django 6.0.2 on 2026-04-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_instastory'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='otp',
            field=models.PositiveBigIntegerField(default=456),
        ),
        migrations.AlterField(
            model_name='instastory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_by', to='myapp.instauser'),
        ),
    ]
