# Generated by Django 6.0.2 on 2026-05-03 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_chatroom_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='myapp.instauser'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.chatroom'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='messages/images/'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text_mssg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='messages/videos/'),
        ),
    ]
