# Generated by Django 6.0.2 on 2026-05-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_messages_sender_alter_messages_chat_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='myapp.chatroom'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='messages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
