# Generated by Django 6.0.2 on 2026-05-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_messages_sender_alter_messages_chat_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='myapp.instauser'),
        ),
    ]
