# Generated by Django 5.0.14 on 2026-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instapost",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_post", to="myapp.instauser"
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="audience",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
